project:
  type: website
  output-dir: _site

website:
  title: "R You Ready - Copy"
  site-url: https://r-you-ready.github.io/HS2025/
  sidebar:
    style: floating
    search: true
    collapse-level: 1
    logo: images/ryouready_logo.png
    active-link: true
    contents:
      - href: front_page.qmd
        text: "Einleitung"
      - href: 0_presentation.qmd
        text: "Präsentationen"
        contents:
          - href: EH_1.qmd
            text: "Einheit 1 - 17.09.2025"
          - href: EH_2.qmd
            text: "Einheit 2 - 24.09.2025"
          - href: EH_3.qmd
            text: "Einheit 3 - 01.10.2025"
          - href: EH_4.qmd
            text: "Einheit 4 - 08.10.2025"
          - href: EH_5.qmd 
            text: "Einheit 5 - 15.10.2025"
          - href: EH_6.qmd
            text: "Einheit 6 - 22.10.2025"
          - href: EH_7.qmd
            text: "Einheit 7 - 29.10.2025"
          - href: EH_8.qmd
            text: "Einheit 8 - 05.11.2025"
          - href: EH_9.qmd
            text: "Einheit 9 - 12.11.2025"
          - href: EH_10.qmd 
            text: "Einheit 10 - 19.11.2025"
          - href: EH_11.qmd
            text: "Einheit 11 - 26.11.2025"
          - href: EH_12.qmd
            text: "Einheit 12 - 03.12.2025"
          - href: EH_13.qmd
            text: "Einheit 13 - 10.12.2025"
          - href: EH_14.qmd
            text: "Einheit 14 - 17.12.2025"
      - href: Übungen.qmd
        text: "Übungen zu den Einheiten"
        contents: 
          - href: hands_on_1.qmd
            text: "Hands on - Block 1 (Woche 1 - 2)"
          - href: hands_on_2.qmd
            text: "Hands on - Block 2 (Woche 3 - 4)"
          - href: hands_on_3.qmd
            text: "Hands on - Block 3 (Woche 5 - 6)"
          - href: hands_on_4.qmd
            text: "Hands on - Block 4 (Woche 7- 8)"
          - href: hands_on_5.qmd
            text: "Hands on - Block 5 (Woche 9 - 10)"
          - href: hands_on_6.qmd
            text: "Hands on - Block 6 (Woche 11 - 12)"
          - href: hands_on_7.qmd
            text: "Hands on - Block 7 (Woche 13)"
      - href: muddiest_points_2.qmd
        text: "Muddiest Points"
        contents:
          - href: muddiest_points_2.qmd
            text: "Muddiest Points 2"
          - href: muddiest_points_3.qmd
            text: "Muddiest Points 3"
      - href: faq.qmd
        text: "FAQ"
        contents:
          - href: rstudio.qmd
            text: "1 RStudio"
            contents:
              - href: fehlermeldungen.qmd
                text: "1.1 Fehlermeldungen"
          - href: codebook.qmd
            text: "2 Codebook"
          - href: datenanalyseplan.qmd
            text: "3 Datenanalyseplan"
          - href: statistic.qmd
            text: "4 Statistik"
          - href: endabgabe.qmd
            text: "5 Abschlussprojekt"
      - href: links_und_ressourcen.qmd
        text: "Links und Ressourcen"
        contents:
          - href: ChatGPT.qmd
            text: "ChatGPT in RStudio"
      - href: leistungsnachweis.qmd
        text: "Leistungsnachweis"
        contents:
          - href: checkliste_abschlussarbeit.qmd
            text: "Checkliste Abschlussarbeit"
          - href: here.qmd
            text: "Probleme beim Rendern"
      - href: LearnR.qmd
        text: "LearnR - Shinyapp"
      - href: about.qmd
        text: "About"

format:
  html:
    toc: true
    toc-expand: false

execute:
  freeze: auto
