{
  "hash": "869fa12ab8547bbd4f193138f56c7657",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"R u Ready? HS2025 | Psychologie der Digitalisierung - Einheit 13\"\nauthor: Sandra Grinschgl, Aaron Friedli, Lars Schilling\nformat: \n  revealjs:\n    title-slide-attributes:\n      data-visibility: hidden\n    theme: [default, ./custom.scss]\n    transition: slide\n    slide-number: true\n    logo: presentation_files/eh1/unibe.png\n    incremental: false\n    self_contained: true\n    show-slide-number: all\n    smaller: true\n    progress: true\n    controls: true\n    embed-resources: true\nbibliography: references.bib\n---\n\n::: {.cell}\n\n:::\n\n\n\n## R u Ready? Reproduzierbare Datenaufbereitung und -analyse mit R\n\nHS 2025<br><br><br> **LV-Leitung**: Dr. Sandra Grinschgl / MSc. Aaron Friedli<br> **Tutor**: BSc. Lars Schilling<br><br><br>**13. Einheit**, 10.12.2025\n\n------------------------------------------------------------------------\n\n## Heute:\n\n<iframe src=\"PDFs/Syllabus.pdf\" width=\"100%\" height=\"600px\">\n\n</iframe>\n\n------------------------------------------------------------------------\n\n## ANOVA - Analysis of Variance\n\nTestet, ob sich Mittelwerte in mehreren Gruppen unterscheiden\n\n**Verschiedene Arten**\n\n-   **One-Way ANOVA (einfaktoriell):**\\\n    Ein Faktor (eine UV) mit mehr als zwei Stufen.\n\n-   **Mehrfaktorielle ANOVA:**\\\n    Zwei oder mehr Faktoren (UVs).\n\n-   **Mixed ANOVA:**\\\n    Kombination aus Within-Subject-Faktoren (Messwiederholung) und Between-Subject-Faktoren.\n\n-   **Multivariate ANOVA (MANOVA):**\\\n    Mindestens zwei abhängige Variablen.\n\n-   **ANCOVA:**\\\n    Kontrolle für eine zusätzliche Drittvariable (Kovariate).\n\n------------------------------------------------------------------------\n\n## Voraussetzungen\n\n-   **Normalverteilung der abhängigen Variablen**\n-   **Varianzhomogenität (Levene-Test)**\n-   **Sphärizität (Mauchly Test) bei Mixed ANOVA**\n\n------------------------------------------------------------------------\n\n## Einfaktorielle ANOVA\n\n**Unterscheiden sich die Mittelwerte der drei Gruppen voneinander?**\n\n**AV**: `mean_rl_all`\n\n**Fixed Effekt:** `group_all` 👉 Dieser Effekt interessiert uns\n\n**Random Intercept:** `(1 | code)` 👉 Irrelevant bei One-Way ANOVA wird aber von der Funktion `afex` verlangt.\n\n<br>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(mean_rl_all ~ group_all, data = dat_full)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)\ngroup   2  0.6889 0.5036\n      156               \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_1 <- aov_4(mean_rl_all ~ group_all + (1 | code), data = dat_full)\n```\n:::\n\n\n\n::: notes\nDer Random Intercept (1 \\| code) ist bei einer einfaktoriellen One-Way ANOVA irrelevant, weil jede Person nur einen einzigen Messwert fuer die AV hat. Die Personenvariabilität wird vom Residuum aufgefangen. Wäre nur relevant bei multilevel strukturen oder messwiederholungen. AFEX ist aber für mixed designs gebaut, und verangt deshalb einen random Intercept obwohl dieser keinemn effekt hat.\n:::\n\n------------------------------------------------------------------------\n\n## Output One-Way ANOVA (Beispiel)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_1 <- aov_4(mean_rl_all ~ group_all + (1 | code), data = dat_full)\n\nsummary(model_1)\n```\n:::\n\n\n\n![](images/EH_13/output_anova.png){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n## ANOVA: Different Package - same result\n\n**BASE-R**\n\n<br>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_aov <- aov(mean_rl_all ~ group_all, data = dat_full)\nsummary(model_aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value Pr(>F)\ngroup_all     2   2.63   1.317   1.045  0.354\nResiduals   156 196.59   1.260               \n```\n\n\n:::\n:::\n\n\n\n<br>\n\n**aov_ez**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_aov_ez <- aov_ez(\n  id = \"code\",\n  dv = \"mean_rl_all\",\n  between = \"group_all\",\n  data = dat_full\n)\n\nsummary(model_aov_ez)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: mean_rl_all\n          num Df den Df    MSE      F      ges Pr(>F)\ngroup_all      2    156 1.2602 1.0448 0.013218 0.3542\n```\n\n\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## ANOVA: Effektstärken\n\ngeneralisiertes **`η2`** & partielles **`η2`** - Wie viel Varianz wird durch die Gruppenzugehörigkeit erklärt?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\neta_squared(model_1, generalized = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type III)\n\nParameter | Eta2 (generalized) |       95% CI\n---------------------------------------------\ngroup_all |               0.01 | [0.00, 1.00]\n\n- Observed variables: All\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\neta_squared(model_1, partial = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type III)\n\nParameter | Eta2 |       95% CI\n-------------------------------\ngroup_all | 0.01 | [0.00, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## Unterschiede generalisiertes und partielles η²\n\n<br>\n\n-   Das generalisierte und `partielle` `η²`sind beides Masse, welche den **Anteil an erklärter Varianz** einer **abhängigen Variable** angeben.\n\n<br>\n\n-   Das `generalisierte η²` berechnet den Anteil der erklärten Varianz einer abhängigen Variable unter **Einbezug der gesamten Varianz, also aller Effekte.**\n\n<br>\n\n-   Das `partielle η²` beachtet bei der Berechnung des Anteils an erklärter Varianz für die **abhängige Variable nicht die gesamte Varianz**, sondern nur jene, welche dem **zuvor definierten Effekt** zugeschrieben werden kann.\n\n::: notes\n> **Partielles Eta-Quadrat:** Wie gross ist der Effekt dieses Faktors, wenn ich alle anderen Einfluessen ignoriere? Wenn eine Kovariate hinzugefuegt wird und weitere Varianz erklaert, vergroessert sich das partielle Eta-Quadrat tendenziell, da der verbleibende Fehleranteil kleiner wird.\n>\n> **Generalisertes Eta-Quadrat:** Wie gross ist der Effekt im gesamten Datensatz, also unter Beruecksichtigung aller anderen Quellen der Varianz?\n:::\n\n------------------------------------------------------------------------\n\n## Post-Hoc t-Tests mit `pairs`\n\n**Verschiedene Möglichkeiten**\n\n-   Klassische t-Tests, wie im Paper und in EH 12\n\n<br>\n\n-   Schneller mit `pairs()`, womit alle möglichen Vergleiche simultan berechnet werden (aber ohne Effektstärken) –\\> Ergänzung für Fortgeschrittene im Hands-On!\n\n<br>\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast        estimate    SE  df t.ratio p.value\n above - below    -0.2925 0.218 156  -1.341  0.3747\n above - control  -0.0443 0.218 156  -0.203  0.9775\n below - control   0.2481 0.218 156   1.138  0.4924\n\nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\n\n-   Optimalerweise: Präregistrieren, welche Post-Hoc-Tests berechnet werden und wie diese korrigiert werden sollen\n\n------------------------------------------------------------------------\n\n## Korrektur für multiples Testen:\n\n![](images/EH_13/Korrekturen.png){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n## Reminder 2x3 ANOVA\n\n**AV** = Rating\n\n**Between Subjects Faktor** = Feedbackgruppe (`below` vs. `control` vs. `above`)\n\n**Within Subjects Faktor:** Messzeitpunkt (Messwiederholter Faktor, `pre 1` vs. `pre 4`)\n\n![](images/EH_12/original_results_1.png){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n## 2x3 mixed ANOVA: Vorbereitungen\n\n***Mixed-ANOVA mit `afex`***\n\n<br>\n\n**AV** = Rating\n\n<br>\n\n**Between Subjects Faktor** = Feedbackgruppe (`below` vs. `control` vs. `above`)\n\n<br>\n\n**Within Subjects Faktor:** Messzeitpunkt (Messwiederholter Faktor, `pre 1` vs. `pre 4`)\n\n👉 Long Datensatz\n\n***Muster:***\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmixed_anova <- aov_4(AV ~ between_factor + (messwiederholter_faktor | ID) data = dat_full_long)\n```\n:::\n\n\n\n------------------------------------------------------------------------\n\n## Beispielhafter Output mit **η2**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmixed_anova <- aov_4(rating ~ group_all + (time_rating | code), data = dat_full_long, anova_table = list(es = c(\"ges\" ,\"pes\")))\n\n\nsummary(mixed_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nUnivariate Type III Repeated-Measures ANOVA Assuming Sphericity\n\n                      Sum Sq num Df Error SS den Df  F value\n(Intercept)           8198.9      1   500.58    156 2555.113\ngroup_all              126.7      2   500.58    156   19.736\ntime_rating             42.0      1   288.70    156   22.668\ngroup_all:time_rating   74.4      2   288.70    156   20.090\n                                     Pr(>F)    \n(Intercept)           < 0.00000000000000022 ***\ngroup_all                     0.00000002286 ***\ntime_rating                   0.00000436406 ***\ngroup_all:time_rating         0.00000001724 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nmixed_anova$anova_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnova Table (Type 3 tests)\n\nResponse: rating\n                      num Df den Df    MSE      F     pes      ges\ngroup_all                  2    156 3.2088 19.736 0.20193 0.138283\ntime_rating                1    156 1.8507 22.668 0.12687 0.050468\ngroup_all:time_rating      2    156 1.8507 20.090 0.20481 0.086102\n                             Pr(>F)    \ngroup_all             0.00000002286 ***\ntime_rating           0.00000436406 ***\ngroup_all:time_rating 0.00000001724 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmixed_anova <- aov_4(rating ~ group_all + (time_rating | code), data = dat_full_long, anova_table = list(es = c(\"ges\" ,\"pes\")))\n\n\nsummary(mixed_anova)\nmixed_anova$anova_table\n```\n:::\n\n\n\n![](images/EH_13/output_2x3_anova.png){fig-align=\"center\"}\n\n------------------------------------------------------------------------\n\n## Vergleich mit @grinschgl2021\n\nIm Paper wurde nur das reine **η2 berichtet. Berechnet mit `eta_squared()`** aus dem Package `effectsize`.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# Effect Size for ANOVA (Type III)\n\nParameter             | Eta2 |       95% CI\n-------------------------------------------\ngroup_all             | 0.12 | [0.05, 1.00]\ntime_rating           | 0.04 | [0.01, 1.00]\ngroup_all:time_rating | 0.07 | [0.02, 1.00]\n\n- One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n:::\n\n\n\n<br>\n\nWe observed a main effect of the factor **“feedback group”, F(2, 156) = 19.74, p \\< 0.001, η2 = 0.12**, as well as a main effect of the factor “time of pre-rating”, **F(1, 156) = 22.67, p \\< 0.001, η2 = 0.04**. Most importantly, we also found a significant interaction between these factors, **F(2, 156) = 20.09, p \\< 0.001, η2 = 0.07**.\n\n------------------------------------------------------------------------\n\n## Verletzungen der Voraussetzungen in ANOVAs\n\n**Normalverteilung (one-way ANOVA)**\n\n-   `Kruskal-Wallis-Test` –\\> Besonders robust gegen Verletzungen der Normalverteilungsannahme\n\n**Varianzhomogenität**\n\n-   Einfaktoriell: `Welch-ANOVA`\n\n**Mixed ANOVA**\n\n-   Relativ robust gegenüber Verletzungen der Normalverteilung\n\n<!-- -->\n\n-   Robuste ANOVA mit `WRS2` Paket\n\n-   Multilevel Model mit `lme4`\n\nBei @grinschgl2021 wurde dies aber außer Acht gelassen. Auf jeden Fall sollte man sich im Vorfeld der Datenerhebung überlegen ob und wie man Voraussetzungen überprüft und wie man bei potenziellen Verletzungen vorgeht.\n\n------------------------------------------------------------------------\n\n## Verletzung Sphärizität\n\n**Beispiel aus den Daten Hausübung:**\n\n-   Der **Mauchly-Test** ist relevant bei mindestens **drei Within-Faktoren** (z.B bei der Hausübung) .\n\n-   Sollte nicht signifikant sein, sodass wir **Sphärizität** annehmen können (ähnlich zum Levene Test).\n\n-   Der Test wird automatisch ausgegeben. Wenn nicht signifikant ist Sphärizität gegeben, asonsten muss korrigiert werden. 👉 Werte nach **Greenhouse-Geisser-Korrektu**r interpretieren.\n\n    -   Diese werden mit model\\$anova_table automatisch ausgegeben. Mit `summary()` bekommt man in der ersten Tabelle die unkorrigierten Werte. Beispiel:\n\n![](images/EH_13/Mauchly_Test.png){fig-align=\"center\"}\n\n::: notes\nSphärizität in der Statistik ist eine Annahme für Varianzanalysen mit Messwiederholung (Repeated Measures ANOVA) und bedeutet, dass die Varianzen der Differenzen zwischen allen Paaren von Messzeitpunkten gleich sind, was eine Art „Homogenität der Differenzen“ darstellt. Bei zwei Zeitpunkten gibt es nur eine differenz, also muss sphärizität gegeben sein (weil es keine zweite oder dritte differenz gibt mit der man vergleichen könnte).\n\nGreenhouse–Geisser verkleinert die Freiheitsgrade, um p-Werte zu korrigieren, wenn Sphärizität verletzt ist.\\\nJe stärker die Verletzung, desto konservativer die Korrektur.\n:::\n\n------------------------------------------------------------------------\n\n## Heute haben wir:\n\n-   ANOVAs kennengelernt\n\n-   Post-hoc Tests und Effektstärken berechnet\n\n-   Vorausetzungsprüfungen und Alternativen angeschaut\n\n------------------------------------------------------------------------\n\n## Bis nächste Woche:\n\n-   **Muddiest Points!!** Bis Sonntag! siehe Ilias EH 13\n\n-   **Hausübung** bis Freitag **und Peerfeedback** bis Mittwoch**!**\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}