{
  "hash": "603f04311ae266a468d06a56984732fb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands On – Analyze (Einheiten 11 und 12)\"\neditor: visual\nbibliography: references.bib\n---\n\n::: {.cell}\n\n:::\n\n\n\n**Bei Bedarf findest du hier nochmals die Slides zu Einheit 10:**\\\n\n<iframe src=\"EH_10.html\" width=\"100%\" height=\"500px\">\n\n</iframe>\n\n# Lernziele\n\n✅ ggplot2\n\n✅ Korrelationen\n\n✅ Regressionen\n\n✅ t-Tests\n\n::: callout-important\nFür die heutigen Übungen benötigen wir den **Wide Datensatz** `dat_full` sowie den **Long Datensatz** `dat_long`\n:::\n\n------------------------------------------------------------------------\n\n## Visualize - Übungen zu `ggplot2`\n\n[📚 Einführung in R - Kapitel 5](https://methodenlehre.github.io/einfuehrung-in-R/chapters/05-plotting.html)\n\n[📚 R for Data Science - Kapitel 1](https://r4ds.hadley.nz/data-visualize.html)\n\n[📚R for Data Science - Kapitel 11](https://r4ds.hadley.nz/communication.html)\n\n::: {.callout-note collapse=\"true\"}\n### Tabelle mit häufig verwendeten Geoms()\n\n| Geom | Funktion | Einsatzbereich | Bild / Beispiel |\n|----|----|----|----|\n| **geom_point()** | Streudiagramm | Zwei numerische Variablen vergleichen (x = Var1, y = Var2) | ![](images/EH_10/geom_point.png) |\n| **geom_jitter()** | Jitter-Plot | Punkte leicht versetzen, um Überlappung zu vermeiden (v. a. bei kategorialem x) | ![](images/EH_10/geom_jitter.png) |\n| **geom_line()** | Liniendiagramm | Werteverlauf Über kontinuierliche x-Achse darstellen | ![](images/EH_10/geom_line.png) |\n| **geom_bar()** | Balkendiagramm | Häufigkeiten oder Aggregationen für Kategorien (x = Gruppe) | ![](images/EH_10/geom_bar.png) |\n| **geom_histogram()** | Histogramm | Verteilung einer numerischen Variable (x = Wert) | ![](images/EH_10/geom_histogram.png) |\n| **geom_boxplot()** | Boxplot | Verteilungen über Gruppen vergleichen (x = Gruppe, y = Wert) | ![](images/EH_10/geom_boxplot.png) |\n:::\n\n::: {.callout-note collapse=\"true\"}\n## Cheatsheet ggplot2\n\n<iframe src=\"PDFs/ggplot.pdf\" width=\"100%\" height=\"500px\">\n\n</iframe>\n:::\n\n**Im folgenden wollen wir Figure 4 aus @grinschgl2021 reproduzieren:**\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](loesung_6_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n### **Vorbereitungen:**\n\nUm die Mittelwerte plotten zu können, müssen wir die Gruppenmittelwerte und Standardfehler berechnen. Passe dafür den Codeblock an:\n\nIm Hands-on Block 4 haben wir bereits mit *dplyr* die MMQ-Skalenwerte „mmq_mean“ pro Person berechnet. Nutze nun die *dplyr*-Funktionen, insbesondere `group_by()`, um den durchschnittlichen MMQ-Wert pro Gruppe (`group_all`) sowie den Standardfehler zu berechnen. Die Formel für den Standardfehler lautet: **SE = SD / √n** und kann z.b so berechnet werden. `se_mmq = sd(mmq_mean) / sqrt(n())` . Ergänze den Code unten mit den nötigen Angaben. Lege group_all in deinem summary als Faktor fest mit den Levels in der Reihenfolge: \"below\", \"control\", \"above\".\n\n::: {.callout-note collapse=\"true\"}\nDer **Standardfehler des Mittelwerts (SEM)** beschreibt **wie stark der geschätzte Stichprobenmittelwert zufällig vom wahren Populationsmittelwert abweichen kann**. Er ist damit ein **Mass für die Präzision** des Mittelwerts.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_full <- dat_full |> \n  mutate(mmq_mean = rowMeans(select(dat_full, starts_with(\"question\")))\n\n\ngroup_summary <- dat_full %>%\n  group_by(XXXXXXX) %>%\n  summarize(\n    group_mean_mmq = mean(XXXXXX),\n    se_mmq = sd(XXXXXX) / sqrt(n())\n  )\n\ngroup_summary$group_all <- factor(group_summary$group_all,\n                                  levels = c(\"XXXXX\", \"XXXXX\", \"XXXXX\"))\n```\n:::\n\n\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_full <- dat_full |> \n  mutate(mmq_mean = rowMeans(select(dat_full, starts_with(\"question\"))))\n\n\ngroup_summary <- dat_full %>%\n  group_by(group_all) %>%\n  summarize(\n    group_mean_mmq = mean(mmq_mean),\n    se_mmq = sd(mmq_mean) / sqrt(n())\n  )\n\ngroup_summary$group_all <- factor(group_summary$group_all,\n                                  levels = c(\"below\", \"control\", \"above\"))\n```\n:::\n\n\n:::\n\n### **1. Erstelle einen leeren Plot und gib deinen Datensatz an**\n\nBeginne mit:\n\n-   `ggplot()` und deinem Datensatz\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_base <- group_summary |> \n  ggplot()\n```\n:::\n\n\n:::\n\n### **2. Definiere die Aesthetic Mappings**\n\nLege fest:\n\n-   welche Variable auf der **x-Achse** liegt\n\n-   welche Variable auf der **y-Achse** liegt\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_base_updated <- plot_base +\n  aes(x = group_all, y = group_mean_mmq)\n```\n:::\n\n\n:::\n\n### **3. Füge `geom_col()` dem Plot hinzu**\n\nDamit zeichnest du die Balken für die Gruppenmittelwerte.\n\n-   `color =` für Konturen\n\n-   `fill =` für die Füllfarben der Balken\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_base_updated <- plot_base_updated +\n  geom_col(fill = \"gray\", color = \"black\")\n```\n:::\n\n\n:::\n\n### **4. Füge Fehlerbalken hinzu**\n\nNutze `geom_errorbar()` und definiere innerhalb von `aes()`:\n\n-   `ymin = mean - se` - Füge die passenden Variablen ein.\n\n-   `ymax = mean + se` - Füge die passenden Variablen ein.\n\nPasse die Breite der Fehlerbalken mit `width =` an.\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_base_updated <- plot_base_updated +\n  geom_errorbar(\n    aes(ymin = group_mean_mmq - se_mmq, ymax = group_mean_mmq + se_mmq),  \n    width = 0.2,\n    color = \"black\"\n  )\n```\n:::\n\n\n:::\n\n### **5. Füge Titel und Achsenbeschriftungen hinzu**\n\nNutze dafür `labs()`. Verändere das theme zu `theme_classic()`\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_base_updated <- plot_base_updated +\n  labs(\n    x = \"Feedback Group\",\n    y = \"Mean MMQ Ratings\",\n    title = \"Group Means of Mean MMQ with SE Error Bars\"\n  ) +\n  theme_classic()\n```\n:::\n\n\n:::\n\n### **6. Stelle sicher, dass der vollständige Wertebereich sichtbar ist**\n\n-   mit `ylim(0, 4)`\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_final <- plot_base_updated +\n  ylim(0, 4)\nplot_final\n```\n\n::: {.cell-output-display}\n![](loesung_6_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n:::\n\n------------------------------------------------------------------------\n\nNun wollen wir den zweiten Plot aus @grinschgl2021 reproduzieren.\n\nErgänze dafür den folgenden Code an den nötigen Stellen mit den passenden Werten und Argumenten.\n\n-   Lade zuerst den in der letzten Woche gespeicherten *Long-Datensatz*.\n\n-   Ersetze anschliessend die Platzhalter **\"XXXXXX\"** durch die erforderlichen Werte, um den Plot zu reproduzieren.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescriptives <- dat_long |> \n  group_by(XXXXXX, XXXXXXX) |> \n  summarize(N = length(rating),\n               mean_d = mean(rating),\n               sd_d   = sd(rating),\n               se_d   = sd_d / sqrt(N)\n)\n\ndescriptives$group_all <- factor(descriptives$group_all, c(\"above\", \"control\", \"below\"))\n\nrate_plot <- descriptives |> \n  ggplot(aes(x = XXXXXX, \n             y = XXXXXX, \n             group = XXXX)) \n\nrate_plot +\n  geom_line(aes(color = group_all, linetype = group_all), size = 1.2) +\n  geom_errorbar(aes(ymin = mean_d - se_d, ymax = mean_d + se_d), width = .1) +\n  scale_color_manual(values = c(\"green4\", \"red\", \"black\")) +\n  theme_classic() +\n  labs(title = \"XXXXXXX\") +\n  ylab(\"XXXXXXXX\") +\n  xlab(\"XXXXXXXXX\") +\n  theme(plot.title = element_text(hjust = 0.5, size = 12, face = \"bold\"), \n        axis.text = element_text(size = 11), axis.title = element_text(size = 14))\n```\n:::\n\n\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescriptives <- dat_long |> \n  group_by(group_all, time_rating) |> \n  summarize(N = length(rating),\n               mean_d = mean(rating)*10,\n               sd_d   = sd(rating)*10,\n               se_d   = sd_d / sqrt(N)\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`summarise()` has grouped output by 'group_all'. You can override using the\n`.groups` argument.\n```\n\n\n:::\n\n```{.r .cell-code}\ndescriptives$group_all <- factor(descriptives$group_all, c(\"above\", \"control\", \"below\"))\n\nrate_plot <- descriptives |> \n  ggplot(aes(x = time_rating, \n             y = mean_d, \n             group = group_all)) \n\nrate_plot_updated <- rate_plot +\n  geom_line(aes(color = group_all, linetype = group_all), size = 1.2) +\n  geom_errorbar(aes(ymin = mean_d - se_d, ymax = mean_d + se_d), width = .1) +\n  scale_color_manual(values = c(\"green4\", \"red\", \"black\")) +\n  theme_classic() +\n  labs(title = \"Subjective Performance Ratings \") +\n  ylab(\"Percentile Rank\") +\n  xlab(\"Time\") +\n  theme(plot.title = element_text(hjust = 0.5, size = 12, face = \"bold\"), \n        axis.text = element_text(size = 11), axis.title = element_text(size = 14))\nrate_plot_updated\n```\n\n::: {.cell-output-display}\n![](loesung_6_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n:::\n\n-   Speichere deinen Plot als PNG Datei ab.\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(\n  \"rate_plot.png\",\n  plot = rate_plot_updated,\n  width = 10,\n  height = 6,\n  dpi = 300\n)\n```\n:::\n\n\n:::\n\n------------------------------------------------------------------------\n\n# Inferenzstatistik\n\n::: {.callout-note collapse=\"true\"}\n## Cheatsheets Statistik\n\n<iframe src=\"PDFs/stat_1.pdf\" width=\"100%\" height=\"500px\">\n\n</iframe>\n\n<iframe src=\"PDFs/stat_3.pdf\" width=\"100%\" height=\"500px\">\n\n</iframe>\n:::\n\n## Korrelationen:\n\n-   Wähle zwei metrische Variablen aus dem Wide Datensatz aus. Berechne die Korrelation mit `cor.test()` für diese beiden Variablen.\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(dat_full$mean_d1_all, dat_full$mean_d_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  dat_full$mean_d1_all and dat_full$mean_d_all\nt = 16.806, df = 157, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.7381602 0.8511386\nsample estimates:\n      cor \n0.8016982 \n```\n\n\n:::\n:::\n\n\n:::\n\n<!-- -->\n\n-   Finde den Korrelationskoeffizienten *r*, den *p*-Wert und die Freiheitsgrade (df). Versuche das Ergebnis zu interpretieren.\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\nIn dem von uns gewählten Beispiel wurde die Korrelation von `mean_d1_all` mit `mean_d_all` berechnet. Der Korrelationskoeffizient r beträgt r = 0.78, was auf eine starke positive Korrelation hinweist. Der p-Wert ist p \\< 0.001, was darauf hindeutet, dass die Korrelation statistisch signifikant ist. Die Freiheitsgrade (df) betragen 157, was auf die Anzahl der Beobachtungen minus 2 zurückzuführen ist (n-2). Das die Dauer bis zur ersten Fensteröffnung und die Dauer des gesamten Trials zusammenhängen war inhaltlich zu erwarten.\n:::\n\n<!-- -->\n\n-   Rufe die Hilfefunktion von `cor.test()` auf. Welche Anpassungen kannst du vornehmen, um die Korrelation einseitig (z.B. nur positiver Zusammenhang) und mit der Spearman-Methode zu berechnen?\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n?cor.test\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nstarte den http Server für die Hilfe fertig\n```\n\n\n:::\n\n```{.r .cell-code}\n# Für eine einseitige Korrelation kannst du das Argument `alternative` verwenden, z.B. `alternative = \"greater\"` für eine positive Korrelation.\ncor.test(dat_full$mean_d1_all, dat_full$mean_d_all, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  dat_full$mean_d1_all and dat_full$mean_d_all\nt = 16.806, df = 157, p-value < 2.2e-16\nalternative hypothesis: true correlation is greater than 0\n95 percent confidence interval:\n 0.7494301 1.0000000\nsample estimates:\n      cor \n0.8016982 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Für die Spearman-Methode kannst du das Argument `method` verwenden, z.B. `method = \"spearman\"`.\ncor.test(dat_full$mean_d1_all, dat_full$mean_d_all, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  dat_full$mean_d1_all and dat_full$mean_d_all\nS = 159836, p-value < 2.2e-16\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.7614103 \n```\n\n\n:::\n:::\n\n\n:::\n\n::: {.callout-note collapse=\"true\"}\n### Korrelationen\n\nLinearer Zusammenhang (Kovarianz) zweier Variablen. Positive Korrelation = hohe Ausprägungen einer Variable hängen mit hohen Ausprägungen einer anderen Variable zusammen. Negative Korrelation = Hohe Ausprägungen einer Variable hängen mit niedrigen Ausprägungen einer anderen Variable zusammen. Korrelationskoeffizient *r* kann von -1 bis +1 gehen. Der Korrelationstest testet ob r sich signifikant von 0 (kein Zusammenhang unterscheidet). Für Pearson Korrelationen sollte die Normalverteilung der Residuen gegeben sein. Alternative: Spearman Korrelation.\n:::\n\n------------------------------------------------------------------------\n\n## Regressionen\n\n::: {.callout-note collapse=\"true\"}\n### **Tabelle: Funktionen für Regressionen und verwandte Analysen in R**\n\n| Funktion | Beschreibung |\n|----|----|\n| **lm(y \\~ x)** | Einfache lineare Regression mit einer abhängigen Variablen *y* und einem Prädiktor *x*. |\n| **lm(y \\~ x1 + x2)** | Multiple Regression mit einer abhängigen Variablen *y* und zwei Prädiktoren *x1* und *x2*. |\n| **summary()** | Gibt die Ergebnisse der Regressionsanalyse für ein Regressionsmodell aus. |\n| **confint()** | Konfidenzintervalle für die Regressionskoeffizienten. |\n| **fitted()** | Vorhergesagte Werte des Regressionsmodells. |\n| **resid()** | Residuen des Regressionsmodells. |\n| **predict()** | Vorhergesagte Werte für bestimmte Werte der Prädiktorvariablen. |\n| **anova()** | Vergleicht die Determinationskoeffizienten zweier Regressionsmodelle mit einem F-Test. |\n| **vif()** \\* | Variance Inflation Factors (VIF) für jeden Prädiktor; aus dem *car*-Paket. |\n\n\\* aus zusätzlichen Paketen\n:::\n\n-   Paket `„car“` installieren und laden.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Paket 'car' wurde unter R Version 4.5.2 erstellt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLade nötiges Paket: carData\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttache Paket: 'car'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDas folgende Objekt ist maskiert 'package:dplyr':\n\n    recode\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDas folgende Objekt ist maskiert 'package:purrr':\n\n    some\n```\n\n\n:::\n:::\n\n\n\n-   Mach aus deiner davor berechneten Korrelation nun ein Regressionsmodel mit der Funktion `model <- lm(outcome ~ predictor, data)`. Schau dir den Output mit `summary(model)` an und versuche ihn zu interpretieren.\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_1 <- lm(mean_d1_all ~ mean_d_all, data = dat_full)\n\nsummary(model_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean_d1_all ~ mean_d_all, data = dat_full)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-9.5963 -1.2404 -0.1045  1.0541  8.3688 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -6.49579    0.81643  -7.956  3.3e-13 ***\nmean_d_all   0.31750    0.01889  16.806  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 2.216 on 157 degrees of freedom\nMultiple R-squared:  0.6427,\tAdjusted R-squared:  0.6404 \nF-statistic: 282.4 on 1 and 157 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nMit `summary(model_1)` erhalten wir Informationen über das Regressionsmodell. Der Koeffizient für `mean_d_all` zeigt an, wie stark sich `mean_d1_all` ändert, wenn `mean_d_all` um eine Einheit steigt. Der p-Wert für diesen Koeffizienten ist signifikant (p \\< 0.001), was darauf hinweist, dass `mean_d_all` Prädiktor signifikant zur Vorhersage der abhängigen Variable `mean_d1_all` beiträgt. Das R-Quadrat (R²) beträgt 0.64, was bedeutet, dass etwa 64% der Varianz in `mean_d1_all` durch `mean_d_all` erklärt wird.\n\nWie die folgende logische Abfrage zeigt, entspricht die Wurzel von R-Squared der Korrelation zwischen den beiden Variablen.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(dat_full$mean_d1_all, dat_full$mean_d_all) == sqrt(summary(model_1)$r.squared)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n:::\n\n-   Ergänze das Modell nun um eine weitere Prädiktorvariable (mit + Variable), sodass du eine multiple Regression berechnest. Hier müssen wir auf Multikollinearität testen – mit `vif(model)` aus dem „car“ Paket (die Werte sollten größer als 0.10 sein, sodass keine Multikollinearität vorliegt). Berechne auch die Konfidenzintervalle der Beta-Koeffizienten mit `confint(model)`.\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_2 <- lm(mean_d1_all ~ mean_d_all + mean_rl_all, data = dat_full)\n\nsummary(model_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean_d1_all ~ mean_d_all + mean_rl_all, data = dat_full)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-5.9478 -1.0924 -0.0321  0.7889  7.6809 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.22170    0.95106   0.233    0.816    \nmean_d_all   0.30716    0.01504  20.429   <2e-16 ***\nmean_rl_all -1.20577    0.12494  -9.651   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.759 on 156 degrees of freedom\nMultiple R-squared:  0.7763,\tAdjusted R-squared:  0.7734 \nF-statistic: 270.7 on 2 and 156 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nvif(model_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n mean_d_all mean_rl_all \n   1.005097    1.005097 \n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(model_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 2.5 %     97.5 %\n(Intercept) -1.6569151  2.1003152\nmean_d_all   0.2774643  0.3368628\nmean_rl_all -1.4525580 -0.9589823\n```\n\n\n:::\n:::\n\n\n\nMit summary(model_2) erhalten wir auch Informationen über das neue, multiple Regressionsmodell. Die Koeffizienten für `mean_d_all` und `mean_rl_all` zeigen an, wie stark sich `mean_d1_all` ändert, wenn diese Prädiktoren um eine Einheit steigen. Beide Prädiktoren haben signifikante p-Werte (p \\< 0.001), was darauf hinweist, dass sie signifikant zur Vorhersage der abhängigen Variable beitragen. Das R-Quadrat (R²) beträgt 0.77, was bedeutet, dass etwa 77% der Varianz in `mean_d1_all` durch beide Prödiktoren zusammen erklärt wird.\n\nDie VIF-Werte für beide Prädiktoren sind unter 10, was darauf hinweist, dass keine Multikollinearität vorliegt.\n\nDie Konfidenzintervalle für die Koeffizienten geben den Bereich an, in dem wir mit 95%iger Sicherheit erwarten können, dass die wahren Koeffizientenwerte liegen. Beinhalten diese Konfidenzintervalle die 0 **nicht**, dann gelten die Koeffizienten ebenfalls als signifkant (unterschiedlich zu null).\n:::\n\n:::: {.callout-note collapse=\"true\"}\n**Fortgeschritten/Freiwillig:**\n\nBerechne eine einfache logistische Regression zwischen Strategien (ohne strategies == 3) und Offloading (mean_rl_all) mit dem Wide Datensatz. Nimm das Statistik III Cheatsheet von Dr. Boris Mayer zur Hand. Tipp: Du musst die Strategien in 0 und 1 umkodieren.\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_log <- dat_full |> \n  filter(strategies != 3) |>  # entferne Strategie 3\n  mutate(strategy_bin = if_else(strategies == 1, 0, 1)) # setze alle Strategien 1 auf 0 und 2 auf 1\n\nmodel <- glm(strategy_bin ~ mean_rl_all, # hier soll das Offloading die Vorhersage der Strategiewahl übernehmen\n             data = dat_log,\n             family = binomial)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = strategy_bin ~ mean_rl_all, family = binomial, \n    data = dat_log)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)  \n(Intercept)  -1.3090     0.8468  -1.546   0.1221  \nmean_rl_all   0.3325     0.1613   2.062   0.0392 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 196.19  on 145  degrees of freedom\nResidual deviance: 191.69  on 144  degrees of freedom\nAIC: 195.69\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\n\nEinmal mehr erhalten wir mit `summary()` informationen über das von uns gerechnete Modell. Der Koeffizient für `mean_rl_all` zeigt an, wie sich die Wahrscheinlichkeiten (Log-Odds) der Wahl von Strategie 2 (im Vergleich zu Strategie 1) ändern, wenn `mean_rl_all` um eine Einheit steigt. Der p-Wert für diesen Koeffizienten ist signifikant (p \\< 0.05), was darauf hinweist, dass `mean_rl_all` signifikant zur Vorhersage der Strategiewahl beiträgt.\n:::\n::::\n\n------------------------------------------------------------------------\n\n## *t*-Tests für abhängige Stichproben\n\n::: {.callout-note collapse=\"true\"}\n### **Tabelle: Funktionen für *t*-Tests und verwandte Analysen in R**\n\n| Funktion | Beschreibung |\n|----|----|\n| **t.test** | Allgemeine Funktion für verschiedene t-Tests: Ein-Stichproben-t-Test, t-Test für unabhängige Stichproben und t-Test für abhängige Stichproben. |\n| **t.test(av, mu = x)** | Ein-Stichproben-t-Test. **av** = abhängige Variable. **x** = Vergleichswert der Population. |\n| **t.test(av \\~ uv)** | Welch-t-Test für **unabhängige Stichproben**. **av** = abhängige Variable, **uv** = Gruppenvariable. |\n| **t.test(av \\~ uv, var.equal = TRUE)** | Klassischer t-Test für unabhängige Stichproben (Varianzen vorausgesetzt gleich). |\n| **t.test(av1, av2, paired = TRUE)** | t-Test für **abhängige Stichproben** (z. B. Prä–Post). **av1** und **av2** = gemessene Variablen. |\n| **leveneTest(av, uv)** \\* | Levene-Test auf Varianzhomogenität für unabhängige Gruppen. Aus dem **car**-Paket. |\n| **effsize::cohen.d()** \\* | Berechnet die standardisierte Effektgröße **Cohen’s d** + Konfidenzintervall. Aus dem **effsize**-Paket. |\n\n\\* Funktionen aus zusätzlichen Paketen.\n:::\n\n-   Paket `„effsize“` installieren und laden.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Paket 'effsize' wurde unter R Version 4.5.2 erstellt\n```\n\n\n:::\n:::\n\n\n\n-   Wir wollen einen t-Test für unabhängige Stichproben durchführen, um das Pre 4 Rating der `„above“` und `„below“` Gruppen zu vergleichen. Starte mit einem `leveneTest()` aus dem `„car“` Paket um die Varianzhomogenität zu prüfen. Tipp: Filtere die Daten, sodass nur die beiden Gruppen `„above“` und `„below“` beinhaltet sind (d.h. ohne die Gruppe `„control“`).\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_full_below_above <- dat_full |> \n  filter(group_all != \"control\")\n\ndat_full_below_above$group_all <- as.factor(dat_full_below_above$group_all)\n\nleveneTest(dat_full_below_above$pre4, dat_full_below_above$group_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value Pr(>F)  \ngroup   1  2.8442 0.0947 .\n      104                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nDer Levene Test prüft die Homogenität der Varianzen zwischen den Gruppen. Ein nicht-signifikanter p-Wert (p \\> 0.05) deutet darauf hin, dass die Varianzen in den beiden Gruppen als gleich angenommen werden können. Der vorliegende Test ist nicht signifikant (p = 0.09 \\> 0.05), was darauf hinweist, dass die Varianzen in den Gruppen `„above“` und `„below“` als homogen betrachtet werden können.\n:::\n\n-   Berechne nun den entsprechenden t-Test mit `t.test()`. Du kannst auch die Hilfefunktion zu Rate ziehen. Versuche dann den Output zu verstehen bzw. das Ergebnis zu interpretieren. Tipp: Wenn die Varianzhomogenität gegeben ist (d.h. der Levene Test nicht signifikant ist), muss man `var.equal = TRUE` angeben, ansonsten wird ein `Welch t-Test` berechnet.\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(pre4 ~ group_all, data = dat_full_below_above, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  pre4 by group_all\nt = 7.9845, df = 104, p-value = 1.991e-12\nalternative hypothesis: true difference in means between group above and group below is not equal to 0\n95 percent confidence interval:\n 2.025170 3.363509\nsample estimates:\nmean in group above mean in group below \n           5.966038            3.271698 \n```\n\n\n:::\n:::\n\n\n\nDer students t-Test vergleicht die Mittelwerte der `pre4` Ratings zwischen den Gruppen `„above“` und `„below“`. Der p-Wert weisst auf einen statistisch signifikanten Unterschied der beiden Mittelwerte hin (p \\< 0.05). Das 95%-Konfidenzintervall für den Mittelwertunterschied liegt zwischen 2.03 und 3.36. Das dieser Bereich **nicht** die 0 beinhaltet spricht ebenfalls für die Signifikanz der Mittelwertsunterschiede. Unter Einbezug der beiden Gruppenmittelwerte (`mean in group above` = 5.97 und `mean in group below` 3.27) deutet das Ergebnis darauf hin, dass die `„above“` Gruppe signifikant höhere `pre4` Ratings aufweist als die `„below“` Gruppe.\n:::\n\n-   Nun berechnen wir noch `Cohen‘s d` als Effektstärken-Maß für den Mittelwertsunterschied. Verwende dafür `effsize::cohen.d()`.  Da es `„cohen.D“` auch im Paket `„psych“` gibt, ist es wichtig hier `„effsize::“` voranzusetzen.\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\neffsize::cohen.d(pre4 ~ group_all, data = dat_full_below_above)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCohen's d\n\nd estimate: 1.551045 (large)\n95 percent confidence interval:\n   lower    upper \n1.111706 1.990383 \n```\n\n\n:::\n:::\n\n\n\nCohen's d beträgt 1.55, was auf einen großen Effekt hinweist.\n:::\n\n👉 Und schon haben wir einen der Post-Hoc t-Tests für die 2x3 ANOVA aus Grinschgl et al. (2020) berechnet (notwendig für die Abschlussarbeit)\n\n------------------------------------------------------------------------\n\n## *t*-Tests für abhängige Stichproben\n\n-   Berechne einen *t*-Test für abhängige Stichproben um in der `„control“` Gruppe `Pre 1` und `Pre 4` zu vergleichen. (D.h. filtere zunächst den Datensatz, sodass nur mehr die `„control“` Gruppe\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(datensatz$Variable1, datensatz$Variable2, paired = TRUE) \n```\n:::\n\n\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_full_control <- dat_full |>\n  filter(group_all == \"control\")\n\nt.test(dat_full$pre1, dat_full$pre4, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  dat_full$pre1 and dat_full$pre4\nt = 4.2727, df = 158, p-value = 3.325e-05\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 0.3906256 1.0622046\nsample estimates:\nmean difference \n      0.7264151 \n```\n\n\n:::\n:::\n\n\n\nDer t-Test für abhängige Stichproben (paired = TRUE) vergleicht die Mittelwerte von `pre1` und `pre4` innerhalb der `„control“` Gruppe. Der p-Wert weisst auf einen signifikanten Unterschied zwischen den Mittelwerten dieser beiden Messzeitpunkte hin (p \\< 0.05). Das 95%-Konfidenzintervall für den Mittelwertunterschied liegt zwischen 0.39 und 1.06, umschliesst damit nicht die 0, und zeigt dadurch ebenfalls einen signifikanten Mittelwertsunterschied zwsichen den beiden Messzeitpunkten an. Die Angabe `mean_difference` zeigt an, wie stark der Mittelwert von `pre1` auf `pre4`angestiegen ist (mean difference = 0.73).\n:::\n\n-   Wandle den t-Test nun in einen einseitigen Test mit alternative = „greater“ oder alternative = „less“ um und berechne Cohen‘s d als Effektstärkenmaß (Achtung: paired = True setzen).\n\n::: {.callout-note collapse=\"true\" title=\"Lösung\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(dat_full$pre1, dat_full$pre4, paired = TRUE, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  dat_full$pre1 and dat_full$pre4\nt = 4.2727, df = 158, p-value = 1.663e-05\nalternative hypothesis: true mean difference is greater than 0\n95 percent confidence interval:\n 0.4451208       Inf\nsample estimates:\nmean difference \n      0.7264151 \n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(effectsize)\n\ncohens_d(\n  dat_full$pre1,\n  dat_full$pre4,\n  paired = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFor paired samples, 'repeated_measures_d()' provides more options.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCohen's d |       95% CI\n------------------------\n0.34      | [0.18, 0.50]\n```\n\n\n:::\n:::\n\n\n\nWährend der ungerichtete t-test prüft, ob die Mittelwerte von `pre1` und `pre4` ungleich sind, prüft der gerichtete t-test (alternative = \"greater\") spezifischer, ob der Mittelwert von `pre4` signifikant größer ist als der Mittelwert von `pre1`. Dies ist auch am Ergebnis \"alternative hypothesis: true mean difference is greather than 0\" erkennen. Der Unterschied im `mean_difference` ist allerdings gleich geblieben, ebenso das Resultat der Signifikanzprüfung.\n:::\n\n# Am Ende deiner Übungen - vergiss nicht dein Skript abzuspeichern! 😉\n",
    "supporting": [
      "loesung_6_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}