{
  "hash": "902a10b567518a1885bc9866d8ac5790",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"R u Ready? HS2025 | Psychologie der Digitalisierung - Einheit 11\"\nauthor: \"Sandra Grinschgl, Aaron Friedli, Lars Schilling\"\nformat:\n  revealjs:\n    title-slide-attributes:\n      data-visibility: hidden\n    theme: [default, ./custom.scss]\n    transition: slide\n    slide-number: true\n    logo: presentation_files/eh1/unibe.png\n    incremental: false\n    self_contained: true\n    show-slide-number: all\n    smaller: true\n    progress: true\n    controls: true\n    embed-resources: true\nbibliography: references.bib\n---\n\n::: {.cell}\n\n:::\n\n\n\n## R u Ready? Reproduzierbare Datenaufbereitung und -analyse mit R\n\nHS 2025<br><br><br> **LV-Leitung**: Dr. Sandra Grinschgl / MSc. Aaron Friedli<br> **Tutor**: BSc. Lars Schilling<br><br><br>**11. Einheit**, 24.11.2025\n\n------------------------------------------------------------------------\n\n## Heute:\n\n<iframe src=\"PDFs/Syllabus.pdf\" width=\"100%\" height=\"600px\">\n\n</iframe>\n\n------------------------------------------------------------------------\n\n## Fragen Hands On Block 5?\n\n------------------------------------------------------------------------\n\n## Abbildungen: Visualize\n\n![](images/EH_10/ggplot.png){fig-align=\"center\" width=\"186\"}\n\n------------------------------------------------------------------------\n\n## Visualisierungen: Reproduktion der Figures aus Grinschgl 2021\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](EH_11_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## Visualisierungen\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](EH_11_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## `ggplot2()`\n\nSehr flexibles Paket.\n\n-   Plots werden schrittweise \"befüllt\"\n\n<!-- -->\n\n-   Alle plots beginnen mit `ggplot()` und dem verwendeten Datensatz\n\n-   Mit aes() definieren wir die elemantaren Elemente der Plots - Variablen die geplottet werden sollen\n\n-   mit + können wir geoms, layers und weitere Elemente hinzufügen.\n\n------------------------------------------------------------------------\n\n## `ggplot2()` - Cheatsheet\n\n:::::: {style=\"display: flex; justify-content: space-between; gap: 1rem;\"}\n::: {style=\"flex: 1;\"}\n```         \n```\n\n![](images/EH_10/ggplot1.png)\n:::\n\n::: {style=\"flex: 1;\"}\n```         \n```\n\n![](images/EH_10/ggplot2.png)\n:::\n\n::: {style=\"flex: 1;\"}\n```         \n```\n\n![](images/EH_10/ggplot3.png)\n:::\n::::::\n\n::: notes\nWith ggplot2, you begin a plot with the function ggplot(), defining a plot object that you then add layers to. The first argument of ggplot() is the dataset to use in the graph and so ggplot(data = penguins) creates an empty graph that is primed to display the penguins data, but since we haven’t told it how to visualize it yet, for now it’s empty. This is not a very exciting plot, but you can think of it like an empty canvas you’ll paint the remaining layers of your plot onto.\n\nNext, we need to tell ggplot() how the information from our data will be visually represented. The mapping argument of the ggplot() function defines how variables in your dataset are mapped to visual properties (aesthetics) of your plot. The mapping argument is always defined in the aes() function, and the x and y arguments of aes() specify which variables to map to the x and y axes. For now, we will only map flipper length to the x aesthetic and body mass to the y aesthetic. ggplot2 looks for the mapped variables in the data argument, in this case, penguins.\n\nTo do so, we need to define a geom: the geometrical object that a plot uses to represent data. These geometric objects are made available in ggplot2 with functions that start with geom\\_. People often describe plots by the type of geom that the plot uses. For example, bar charts use bar geoms (geom_bar()), line charts use line geoms (geom_line()), boxplots use boxplot geoms (geom_boxplot()), scatterplots use point geoms (geom_point()), and so on.\n\nZusammenhang bedeutet die Verwendung von +, dass wir einzelne Elemente eines Plot-Objektes zusammenfügen.\n:::\n\n------------------------------------------------------------------------\n\n## Argumente von `ggplot()`\n\n-   Variablen als Aesthetic Mappings definieren\n\n-   Mapping ist immer das zweite Argument (nach dem Datensatz), \"call\" kann also auch verkürzt werden.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- penguins |>\n  ggplot( \n       mapping = \n         aes(x = body_mass_g, \n           y = bill_length_mm))\np\n```\n\n::: {.cell-output-display}\n![](EH_11_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## `ggplot()` - Geoms\n\n-   Layers Hinzufügen z.B. ein geom mit +\n-   Geoms = geometrische Objekte, die die Daten darstellen (z.B. Punkte, Linien)\n-   Muss je nachdem welche Daten man hat und wie man diese darstellen will ausgewählt werden, z.B.\n    -   Kategoriale Variable: `geom_bar()`\n    -   Kontinuierliche Variable: `geom_histogram()`\n    -   2 kontinuierliche Variablen: `geom_point()`, `geom_line()`\n    -   2 Kategoriale Variablen: `geom_count()`\n    -   Kategorial + Kontinuierlich: `geom_boxplot()`, `geom_violin()`\n\n------------------------------------------------------------------------\n\n## `ggplot()` - Geoms\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- p +\n  geom_point()\n\np\n```\n\n::: {.cell-output-display}\n![](EH_11_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## `ggplot()` - Layers\n\n-   Mappings können auch in den Layers definiert werden\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- p + \n  geom_point(aes(x = body_mass_g, \n           y = bill_length_mm))\n\np\n```\n\n::: {.cell-output-display}\n![](EH_11_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## `ggplot()` - Layers\n\n-   Titel + Achsenbeschriftung (= `labs`), Regressionslinien, vereinfachtes Design\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- p +\n  geom_smooth(aes(group = 1), method = \"lm\") +\n  theme_classic() +\n  labs(\n    title = \"Relationship Between Body Mass and Bill Length\",\n    x = \"Body Mass (g)\",\n    y = \"Bill Length (mm)\"\n  )\n\np\n```\n\n::: {.cell-output-display}\n![](EH_11_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n\nmit `theme_` können [verschiedene Formatierungen](https://ggplot2.tidyverse.org/reference/ggtheme.html) gewählt werden. `theme_classic` wird typischerweise für APA7 passende Formatierungen gewählt.\n\n------------------------------------------------------------------------\n\n## `ggplot()` - Verschiedene Layers/Geoms kombiniert\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- penguins |>\n  ggplot(aes(x = island, y = body_mass_g, color = island, shape = sex)) +\n  geom_boxplot() +\n  geom_jitter(alpha = 0.5)+\n  theme_classic()+\n  labs(\n    title = \"Body Mass Per Island and Species\", x = \"Island\", y = \"Body Mass (g)\")\np2\n```\n\n::: {.cell-output-display}\n![](EH_11_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n\n::: notes\nAchtung: Nicht optimal formatiert, weil sonst der Plot zu klein dargestellt wird.\n:::\n\n------------------------------------------------------------------------\n\n## Abbildungen speichern\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggsave(filename = \"my_first_plot.png\", plot = p2)\n```\n:::\n\n\n\n------------------------------------------------------------------------\n\n## Weitere Ressourcen:\n\nViel, viel mehr Möglichkeiten als wir hier besprechen, siehe z.B.:\n\n[**Auflistung von Argumenten**](https://ggplot2.tidyverse.org/reference/index.html)\n\n[**ggplot2 Cheatsheet**](https://posit.co/wp-content/uploads/2022/10/data-visualization-1.pdf)\n\n**R for Data Science – Kapitel 9 & 10:**\\\n[Kapitel „Layers“](https://r4ds.hadley.nz/layers)\n\n[Kapitel „EDA“](https://r4ds.hadley.nz/EDA.html)\n\n[**Weitere Textelemente in Abbildungen (Kapitel 11)**](https://r4ds.hadley.nz/communication)\n\nHier findet man auch weitere Visualisierungsmöglichkeiten & Informationen dazu, wie man verschiedene Plots neben/untereinander abbilden kann.\n\n[Top 50 Visualisierungen mit ggplot2](https://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html#Waffle%20Chart)\n\n[für Animationen, Signifikanztests, Wordclouds usw.](https://exts.ggplot2.tidyverse.org/gallery/)\n\n------------------------------------------------------------------------\n\n# Inferenzstatistik\n\n------------------------------------------------------------------------\n\n## Erinnerung Statistik\n\n-   Forschungsfrage/ Hyptothese aufstellen und Auswahl passender Testverfahren 👉 Bereits im Datenanalyseplan gemacht\n\n[Entscheidungsbaum statistischer Testverfahren](https://etools.fernuni.ch/entscheidungsbaum/main.html)\n\n<br><br>\n\n[Entscheidungsbaum UZH](https://www.methodenberatung.uzh.ch/de/datenanalyse_spss.html)\n\n------------------------------------------------------------------------\n\n## Korrelationen\n\n-   Linearer Zusammenhang zweier Variablen\n-   Positive Korrelation = hohe Ausprägungen einer Variable hängen mit hohen Ausprägungen einer anderen Variable zusammen\n-   Negative Korrelation = Hohe Ausprägungen einer Variable hängen mit niedrigen Ausprägungen einer anderen Variable zusammen\n-   Korrelationskoeffizient *r* kann von -1 bis +1 gehen\n-   Voraussetzung: Normalverteilung der Residuen (siehe EH 10)\n-   Nicht-parametrische Alternative: Spearman Korrelation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(penguins$bill_length_mm, penguins$body_mass_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  penguins$bill_length_mm and penguins$body_mass_g\nt = 13.654, df = 340, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.5220040 0.6595358\nsample estimates:\n      cor \n0.5951098 \n```\n\n\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## Notation\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(scipen = 999)\ncor.test(penguins$bill_length_mm, penguins$body_mass_g)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  penguins$bill_length_mm and penguins$body_mass_g\nt = 13.654, df = 340, p-value < 0.00000000000000022\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.5220040 0.6595358\nsample estimates:\n      cor \n0.5951098 \n```\n\n\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## Hinweise zur linearen Regression\n\n-   Testet den Zusammenhang zwischen zwei Variablen\n-   Einfache lineare Regression = Korrelation\n-   Keine Kausalaussagen möglich (wie auch bei Korrelationen)\n-   Voraussetzungen: Normalverteilung der Residuen, Multikollinearität und Homoskedastizität\n-   Nicht-parametrische Alternative: Poisson-Regression\n\n![](images/EH_11/Regressionen.png){fig-align=\"center\"}\n\n::: notes\nHomoskedastizität bedeutet, dass die Varianz der Residuen in einer Regressionsanalyse   für alle Werte des Prädiktors konstant ist. Das heißt, die Abweichungen der vorhergesagten Werte von den wahren Werten sind in etwa immer gleich groß – unabhängig wie hoch oder niedrig der Wert des Prädiktors ist. Um deine Regressionsanalyse sinnvoll interpretieren zu können, ist es wichtig, dass Homoskedastizität vorliegt. Homoskedastizität bildet deshalb neben einigen weiteren Aspekten (z.B. Vermeidung von Multikollinearität ) eine wichtige Voraussetzung für die lineare Regression. Heteroskedastizität Das Gegenteil von Homoskedastizität ist Heteroskedastizität. In diesem Fall verändert sich die Varianz der Residuen mit ansteigenden oder abfallenden Werten des Prädiktors. Beispielsweise kannst du bei Heteroskedastizität mit deiner Vorhersage systematisch umso weiter daneben liegen, je größer der Prädiktorwert ist, für den du dein Kriterium schätzen möchtest.\n:::\n\n------------------------------------------------------------------------\n\n## Einfache lineare Regressionen\n\n**Argumente**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_1 <- lm(mean_rl_all ~ cvstm_propcorrect, data = dat_full)\n\nsummary(model_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = mean_rl_all ~ cvstm_propcorrect, data = dat_full)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-2.1982 -0.6544 -0.1708  0.7555  3.5717 \n\nCoefficients:\n                  Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)         7.6277     0.8257   9.238 < 0.0000000000000002 ***\ncvstm_propcorrect  -3.2993     1.1202  -2.945              0.00372 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.097 on 157 degrees of freedom\nMultiple R-squared:  0.05236,\tAdjusted R-squared:  0.04632 \nF-statistic: 8.674 on 1 and 157 DF,  p-value: 0.003719\n```\n\n\n:::\n:::\n\n\n\n------------------------------------------------------------------------\n\n## Regression: Output\n\n![](images/EH_11/Regressionsoutput.png){fig-align=\"center\"}\n\n::: notes\nHier eine **sehr kurze, punktuelle Zusammenfassung**:\n\n-   **Intercept (7.63)**: Ausgangswert von *mean_rl_all*, wenn cvstm_propcorrect = 0.\n\n-   **Steigung (-3.30)**: Hoeherer cvstm_propcorrect sagt niedrigeren mean_rl_all voraus (negativer Zusammenhang\n\n-   **p = .0037**: Zusammenhang ist **signifikant**.\n\n-   **Residuen**: Durchschnittliche Abweichung vom Modell ca. 1.10.\n\n-   **R² = 0.052**: Modell erklaert **5% der Varianz** → kleiner Effekt.\n\n-   **F-Test p = .0037**: Das Gesamtmodell ist signifikant.\n\n**Kurz:** Höhere cvstm_propcorrect-Werte gehen mit niedrigeren mean_rl_all-Werten einher, aber das Modell erklaert nur wenig Varianz.\n:::\n\n------------------------------------------------------------------------\n\n### **Tabelle: Funktionen für Regressionen und verwandte Analysen in R**\n\n| Funktion | Beschreibung |\n|----|----|\n| `lm(y ~ x)` | Einfache lineare Regression mit einer abhängigen Variablen *y* und einem Prädiktor *x*. |\n| `lm(y ~ x1 + x2)` | Multiple Regression mit einer abhängigen Variablen *y* und zwei Prädiktoren *x1* und *x2*. |\n| `summary()` | Gibt die Ergebnisse der Regressionsanalyse für ein Regressionsmodell aus. |\n| `confint()` | Konfidenzintervalle für die Regressionskoeffizienten. |\n\n------------------------------------------------------------------------\n\n| Funktion | Beschreibung |\n|----|----|\n| `fitted()` | Vorhergesagte Werte des Regressionsmodells. |\n| `resid()` | Residuen des Regressionsmodells. |\n| `predict()` | Vorhergesagte Werte für bestimmte Werte der Prädiktorvariablen. |\n| `anova()` | Vergleicht die Determinationskoeffizienten zweier Regressionsmodelle mit einem F-Test. |\n| `vif()` \\* | Variance Inflation Factors (VIF) für jeden Prädiktor; aus dem **car**-Paket. |\n\n\\* aus zusätzlichen Paketen\n\n------------------------------------------------------------------------\n\n## Hierarchische Regression\n\n-   Man legt zwei oder mehr Regressionsmodelle an mit zunehmenden Prädiktoren\n\n-   Dann vergleicht man diese Modelle mit `anova(model1, model2)`. Gibt es einen signifikanten Zuwachs an aufgeklärter Varianz (siehe Determinationskoeffizient) von model1 zu model2?\n\nSiehe hier: [**Lineare Regression mit R (einfach, multiple, hierarchisch)**](https://www.youtube.com/watch?v=JzcIKIW6mfc)\n\n------------------------------------------------------------------------\n\n## Heute haben wir:\n\n-   Basics der Datenvisualisierungen kennengelernt\n\n    -   Erstellung von Tabellen\n\n    -   `ggplot()`\n\n-   Korrelationen und Regressionen in R kennengelernt\n\n**Reminder: R Übung bis Freitag 28.11, Peer Feedback über Forum bis 03.12.**\n\n------------------------------------------------------------------------\n\n## **Optionale Slide Korrelation = Einfache lineare Regression**\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  penguins$bill_length_mm and penguins$body_mass_g\nt = 13.654, df = 340, p-value < 0.00000000000000022\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.5220040 0.6595358\nsample estimates:\n      cor \n0.5951098 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = bill_length_mm ~ body_mass_g, data = penguins)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.1251  -3.0434  -0.8089   2.0711  16.1109 \n\nCoefficients:\n              Estimate Std. Error t value            Pr(>|t|)    \n(Intercept) 26.8988724  1.2691478   21.19 <0.0000000000000002 ***\nbody_mass_g  0.0040514  0.0002967   13.65 <0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.394 on 340 degrees of freedom\n  (2 Beobachtungen als fehlend gelöscht)\nMultiple R-squared:  0.3542,\tAdjusted R-squared:  0.3523 \nF-statistic: 186.4 on 1 and 340 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3541557\n```\n\n\n:::\n:::\n",
    "supporting": [
      "EH_11_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}